services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: tinyshop-sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

  products:
    build:
      context: .
      dockerfile: src/Products/Dockerfile
    container_name: tinyshop-products
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      EnableHttpsRedirection: "false"
      ConnectionStrings__ProductsDb: Server=sqlserver,1433;Database=TinyShop;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;
    ports:
      - "5228:8080"
    restart: on-failure

  store:
    build:
      context: .
      dockerfile: src/Store/Dockerfile
    container_name: tinyshop-store
    depends_on:
      - products
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "8080"
      EnableHttpsRedirection: "false"
      ProductEndpoint: http://products:8080
      ProductBrowserEndpoint: http://localhost:5228
      Logging__LogLevel__Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Error
    ports:
      - "5158:8080"
    volumes:
      - store-dataprotection-keys:/root/.aspnet/DataProtection-Keys
    restart: on-failure

  embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    ports:
      - "8001:80"
    command: --model-id sentence-transformers/all-mpnet-base-v2
    volumes:
      - model-cache:/data
    environment:
      HF_HOME: /data

volumes:
  model-cache:
  sqlserver-data:
  store-dataprotection-keys: